---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: document
  path: content/data/photographers.json
  label: Photographer list
- type: document
  path: content/data/info.json
  label: Info Page
- type: heading
  label: Config
- type: document
  path: content/data/config.json
  label: Site info
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
