---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Projectnaam
  config:
    required: true
  description: Projectnaam moet overeenkomen met filename
- type: file
  name: hero_image
  label: hero_image
- name: description
  type: text
  config:
    required: true
  label: Omschrijving
  showOnly:
    value: Allen Ginsberg
- name: projecttype
  type: list
  config:
    use_select: true
    min: 1
    max: 2
    source:
      type: documents
      section: project-types
      file: content/data/projecttypes.json
      path: projecttypes
  label: Projecttype
  description: Selecteer 1 of 2 projecttypes die van toepassing zijn.
- name: properties
  type: field_group
  config: {}
  label: Eigenschappen
  description: Eigenschappen van het project.
- name: jaar_uitvoering
  type: number
  label: Jaar uitvoering
  description: ''
  default: 0
  required: true
  config:
    min: 1950
    max: 2050
    step: 
    required: true
- name: location
  type: text
  config:
    required: false
  label: Locatie
- name: bouwheer
  type: text
  config:
    required: false
  label: Bouwheer
- name: budget
  type: number
  label: Budget
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- type: datetime
  name: date
  label: date
  config:
    required: true
  hidden: true
  default: now
- name: photographer
  type: select
  default: STYLUS Architecten Van Oekelen & Ratinckx
  config:
    required: true
    options: []
    source:
      type: documents
      section: photographer-list
      file: content/data/photographers.json
      path: photographers
  label: Fotograaf
  description: Select photographer. To add a new photographer, go to Photographers
    List
pages:
- content/projects/dm30.md
- content/projects/test04.md
