---
label: Project
hide_body: false
fields:
- name: projectnaam
  type: text
  config:
    required: false
  label: Projectnaam
- name: omschrijving
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Omschrijving
- name: type_project
  type: select
  default: []
  config:
    required: false
    options:
    - Industriebouw
    - Particulier nieuwbouw
    - Particulier renovatie
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type project
- name: foto
  type: file
  config:
    maxSize: 64
  label: Foto
