---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Projectnaam
  config:
    required: true
  description: Titel of naam van het project.
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Omschrijving
  description: Korte omschrijving van het project.
- name: properties
  type: field_group
  config: {}
  fields:
  - name: Jaar van uitvoering
    type: number
    label: Jaar van uitvoering
    description: ''
    default: 0
    required: true
    config:
      min: 1950
      max: 2050
      step: 
      required: true
  - name: Locatie
    type: text
    config:
      required: false
    label: Locatie
  - name: Bouwheer
    type: text
    config:
      required: false
    label: Bouwheer
  - name: Budget
    type: number
    label: Budget
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  label: Eigenschappen
  description: Eigenschappen van het project.
- type: file
  name: hero_image
  label: hero_image
- name: projecttype
  type: list
  config:
    use_select: true
    min: 1
    max: 2
    source:
      type: documents
      section: project-types
      file: content/data/projecttypes.json
      path: projecttypes
  label: Projecttype
  description: Selecteer 1 of 2 projecttypes die van toepassing zijn.
- name: photographer
  type: select
  default: STYLUS Architecten Van Oekelen & Ratinckx
  config:
    required: true
    options: []
    source:
      type: documents
      section: photographer-list
      file: content/data/photographers.json
      path: photographers
  label: Fotograaf
  description: Select photographer. To add a new photographer, go to Photographers
    List
- type: datetime
  name: date
  label: date
  config:
    required: true
  hidden: true
  default: now
pages:
- content/projects/dm30.md
- content/projects/indu01.md
- content/projects/proj02.md
- content/projects/proj05.md
- content/projects/test04.md
