---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Projectnaam
  config:
    required: true
  description: Projectnaam moet overeenkomen met filename
- name: subtitle
  type: text
  config:
    required: true
  label: Subtitel
  showOnly:
    value: Allen Ginsberg
- name: projecttype
  type: tag_list
  default: []
  label: Projecttype
- name: jaar_uitvoering
  type: number
  label: Jaar uitvoering
  description: ''
  default: 0
  required: true
  config:
    min: 1950
    max: 2050
    step: 
    required: true
- name: budget
  type: number
  label: Budget
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- type: file
  name: hero_image
  label: hero_image
- type: datetime
  name: date
  label: date
  config:
    required: true
- name: author
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: documents
      section: author-list
      file: content/data/authors.json
      path: authors
  label: Author
  description: Select author, to add a new author, go to Authors List
pages:
- content/projects/dm30.md
